name: feature_pipeline

on:
  workflow_dispatch:
#  push:
#    branches:
#      - 'master'
  schedule:
    - cron: '0 0 * * *' # runs every day at 00:00

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: execute Feature Pipeline
        env: 
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
        run: python ./pipeline_public_weather_fg_actions.py